apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  strategy:
    canary:
      canaryService: rollouts-demo-canary # canary
      stableService: rollouts-demo-stable # stable
      trafficRouting:
        istio:
          virtualService:
            name: rollouts-demo-vsvc # Istio virtualService
            routes:
            - primary
      canaryMetadata:
        annotations:
          role: rollouts-demo-canary-workload
        labels:
          role: rollouts-demo-canary-workload

      # metadata which will be attached to the stable pods
      stableMetadata:
        annotations:
          role: rollouts-demo-stable-workload
        labels:
          role: rollouts-demo-stable-workload
      steps:
      - setWeight: 20
      - pause: {}         # Manual approve is required
      - setWeight: 40
      - pause: {duration: 60s}
      - setWeight: 60
      - pause: {duration: 60s}
      - setWeight: 80
      - pause: {duration: 60s}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
